language: python
dist: xenial
sudo: false

install:
  - pip install tox

matrix:
  include:
    - python: '3.6'
      env: TOXENV=check36
    - python: '3.8'
      env: TOXENV=check38
    - python: '3.4'
      env: TOXENV=py34
    - python: '3.5'
      env: TOXENV=py35
    - python: '3.6'
      env: TOXENV=py36
    - python: '3.7'
      env: TOXENV=py37
    - python: '3.8'
      env: TOXENV=py38

script:
  - tox

cache:
  pip: true
